site_name: ZMQ's NLP_Learning
site_author: ZMQ
site_description: About learning NLP

theme: 
   name: material

nav: 
   - Index: index.md
   - Home: .\notebook\nlp.ipynb
   - Notebook page: .\notebook\text-preprocessing.ipynb
   - Python file: .\notebook\text-representation.ipynb

plugins:
   - mkdocs-jupyter
      

