site_name: ZMQ's NLP_Learning
site_author: ZMQ
site_description: About learning NLP

theme: 
   name: material
   palette:
      primary: yellow

features: 
   - search.highlight
   - search.share


nav: 
   - Index: index.md
   - Home: .\notebook\nlp.ipynb
   - Notebook page: .\notebook\text-preprocessing.ipynb
   - Python file: .\notebook\text-representation.ipynb

plugins:
   - mkdocs-jupyter
   - search
      
markdown_extensions:
   - abbr
   - attr_list
   - admonition
   - def_list
   - footnotes
   - md_in_html
   - meta # 支持Markdown文件上方自定义标题标签等
   - pymdownx.caret
   - pymdownx.betterem
   - pymdownx.critic
   - pymdownx.details
   - pymdownx.inlinehilite
   - pymdownx.keys
   - pymdownx.mark
   - pymdownx.snippets
   - pymdownx.smartsymbols
   - pymdownx.tilde
   
   - pymdownx.arithmatex:  # latex支持
      generic: true
   - toc:
      permalink: true # 固定标题位置为当前位置
   - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
   - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
   - pymdownx.tabbed:
      alternate_style: true
   - pymdownx.tasklist:
      custom_checkbox: true
   - markdown.extensions.toc:
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
      permalink: "\ue157"

