site_name: ZMQ's NLP_Learning
theme: 
   name: material
   palette:
      scheme: slate

nav: 
   - Home: nlp.ipynb
   - Notebook page: text-preprocessing.ipynb
   - Python file: text-representation.ipynb
plugins:
   mkdocs-jupyter:
      theme: dark
      include_source: True

